### PR TITLE
Resize avatar image to 50x50

### PR DESCRIPTION
**Pull request by Atry**
This PR would significantly reduce the generated file size, avoiding HTTP 413 Payload Too Large error

### CODE REVIEW

**Comment by Atry** [comment]
25x25 might be too fuzzy, when `devicePixelRatio` is not 1.

**Comment by Atry** [comment]
Updated the PR to use 50x50 images

**Comment by HwangTaehyun** [comment]
@Atry Could you rebase it to main? Thank you!

**Comment by Atry** [comment]
Rebased

**Pull request merged**
